packages:
  - application
  - design-system

publicHoistPattern:
  - electron

allowBuilds:
  electron-winstaller: true
  esbuild: true
  msw: false
minimumReleaseAgeExclude:
  - "@types/node@26.6.2"
