name: Package

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  package:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            target: linux
          - name: macOS
            os: macos-latest
            target: mac
          - name: Windows
            os: windows-latest
            target: win
    steps:
      - name: Check Out Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set Up Toolchain
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          runtime: node@26
          cache: true
          require-lockfile: true

      - name: Package Application
        run: pnpm run package:${{ matrix.target }}

      - name: Upload Packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: NovaDeck-${{ matrix.target }}
          path: release/*
          if-no-files-found: error
