name: PR

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Verify Pull Request
        uses: stardwst/__actions/actions/pr-verify@v1
        with:
          required-sections: |
            What
            Why
            Impact
